# Identificación
sonar.projectKey=calculadora-demo
sonar.projectName=Calculadora Demo
sonar.projectVersion=1.0.0

# Código fuente
sonar.sources=src
sonar.tests=test
sonar.language=py

# Reportes de PyTest
sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.python.xunit.reportPath=reports/junit.xml

# Exclusiones
sonar.exclusions=**/__pycache__/**,**/venv/**,**/htmlcov/**

# ── Servidor SonarQube ───────────────────────────────────
sonar.host.url=http://localhost:9000

# Encoding
sonar.sourceEncoding=UTF-8